name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - java-version: 1.8

        - java-version: 11

        - java-version: 12
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
    - uses: actions/checkout@v2
    - run: mvn install --quiet -DskipTests=true -Dgpg.skip=true
    - run: mvn test -B
    - run: mvn clean test jacoco:report coveralls:report -P coverage


